//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int ID_academics { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string specialization { get; set; }
        public Nullable<int> year_rank { get; set; }
    }
}
