//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ID_exam { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> ID_discipline { get; set; }
        public Nullable<int> ID_student { get; set; }
        public Nullable<int> ID_positions { get; set; }
        public string auditorium { get; set; }
        public Nullable<int> score { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual Student Student { get; set; }
    }
}
