//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries2
    {
        public int ID_countries2 { get; set; }
        public string name { get; set; }
        public string capital { get; set; }
        public string part_of_the_world { get; set; }
        public Nullable<decimal> population { get; set; }
        public Nullable<decimal> square { get; set; }
        public Nullable<int> type_control { get; set; }
    }
}
