//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students2
    {
        public int ID_Students2 { get; set; }
        public string last_name { get; set; }
        public string subject { get; set; }
        public string school { get; set; }
        public Nullable<double> points { get; set; }
    }
}
